# Generated by Django 5.2.8 on 2025-11-22 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(help_text='Unique identifier for the image', max_length=255, unique=True)),
                ('grid_cell', models.CharField(blank=True, help_text='Grid cell location', max_length=50, null=True)),
                ('timestamp', models.DateTimeField(help_text='Timestamp of the image capture')),
                ('latitude', models.FloatField(blank=True, help_text='Latitude coordinate', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude coordinate', null=True)),
                ('cloud_cover', models.FloatField(blank=True, help_text='Cloud cover percentage', null=True)),
                ('spatial_resolution', models.FloatField(blank=True, help_text='Spatial resolution in meters', null=True)),
                ('dataset_split', models.CharField(choices=[('train', 'Training'), ('validation', 'Validation'), ('test', 'Test')], default='train', max_length=20)),
                ('embedding_vector', models.TextField(blank=True, help_text='Embedding vector as comma-separated values', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['image_id'], name='sensing_sat_image_i_94f3c0_idx'), models.Index(fields=['timestamp'], name='sensing_sat_timesta_cf0ee4_idx'), models.Index(fields=['grid_cell'], name='sensing_sat_grid_ce_455715_idx')],
            },
        ),
        migrations.CreateModel(
            name='RemoteSensingAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(help_text='Type of analysis performed', max_length=100)),
                ('result_data', models.JSONField(help_text='Analysis results in JSON format')),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score of the analysis', null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the analysis')),
                ('satellite_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='sensing.satelliteimage')),
            ],
            options={
                'verbose_name_plural': 'Remote Sensing Analyses',
                'ordering': ['-performed_at'],
            },
        ),
    ]
